### ISSUE TITLE
Proper null handling

### ISSUE THREAD

**Issue by ZakTaccardi** [f2prateek/rx-preferences#101]
I need to be able to *observe* a preference's value (or lack of value or if it has been cleared). It's very important to be able to keep the stream alive.

`Observable<Optional<Boolean>>` //note Optional is my own custom class

Would it be possible to pass in some function to handle a custom mapping when the preference is null?

**Comment by f2prateek** [comment]
Use a sentinel value for the default. When the preference does not exist, the default value is emitted. Check the value against the sentinel value, if they're equal the value does not exist.

**Comment by ZakTaccardi** [comment]
> Use a sentinel value for the default. When the preference does not exist, the default value is emitted. Check the value against the sentinel value, if they're equal the value does not exist.

This causes two problems

* Can't use a sentinel value for a `Boolean` optional. We only have `true` and `false`..
* Duplicating extra work across users of this library. Ideally, the library itself should bear this burden

I know RxJava2's lack of nullability without a proper optional is rather an annoying problem to solve. Worst case scenario, an optional implementation (maybe call it `EmptyPreference<T>`) would be better than nothing.

**Comment by ZakTaccardi** [comment]
Please re-open @f2prateek .

Currently there's no way to observe a nullable boolean preference. can't use a sentinel value, when you have two options - true or false.

**Comment by f2prateek** [comment]
If you need to know about the nullability, a boolean sounds like the wrong fit with the current API. You can use integers or enums or a custom object instead.

Feel free to re-open and suggest  a concrete proposal.

**Comment by ZakTaccardi** [comment]
> You can use integers or enums or a custom object instead.

This could certainly work, but does android treat `Boolean` vs `String` preferences differently? What happens if you access a `Boolean` preference with `sharedPrefs.getString(key)` where the key already exists in a boolean preference. Does it just return `true`?

I need to be able to completely interop with the other non-reactive ways the app (co-workers) access the preference.

Ultimately I still suggest some type of converter a la Retrofit style to enable usage of custom `Optional<T>` types.
