### ISSUE TITLE
Use case for commit...

### ISSUE THREAD

**Issue by NightlyNexus** [f2prateek/rx-preferences#110]
[In a developer feature](https://github.com/JakeWharton/u2020/issues/323), I want to kill the process immediately after setting a preference value. So, I need to ensure the value is written to the disk (using commit instead of apply).

This is a pretty rare use case, and I can't yet think of an API to propose.

**Comment by NightlyNexus** [comment]
I'm thinking one could implement Preference and copy the implemention but with commit. That's not too bad!

**Comment by carlol** [comment]
Hi,
any plan to add a new methods with commit method?
