### ISSUE TITLE
2.0 Release

### ISSUE THREAD

**Issue by PaulWoitaschek** [f2prateek/rx-preferences#112]
It seems like the last real change was for RC3 in August 2017. What about releasing the 2.0?

**Comment by kevintok** [comment]
Looking to use this too, any news?

**Comment by f2prateek** [comment]
Use the RC? There isn't anything on `master` to be released. You'll see here if there's an update.

**Comment by tbsandee** [comment]
Running into a case where there is resistance using the library from QA because it is not "released". Wondering if you just lost your release keys....

**Comment by JakeWharton** [comment]
Keys are not needed to release libraries.

**Comment by f2prateek** [comment]
2.0.0 is now released https://github.com/f2prateek/rx-preferences/blob/master/CHANGELOG.md#version-200-22-04-2018
