### ISSUE TITLE
transforming to single

### ISSUE THREAD

**Issue by worldsnas** [f2prateek/rx-preferences#117]
Hi and thank you for your great effort on this library.
there is only one thing I'd like to ask:
when i use `.asObservable()` to get the result as a stream so I can transform it later in the chain (using `concatMap` or `singleOrError` or even `toList`) the chain won't work and `.subscribe()` won't get called.
as far as I could understand the reason for this problem is that you are using `OnSharedPreferenceChangeListener` to get changes not the value therefore by not calling `.complete()` in the `onCreate` of your observable. we won't be able to transform the chain to any form of `Single` (since it needs the sourceObservable to call onComplete to carry on)

is there any way we can do the transformation without breaking the chain?

**Comment by JakeWharton** [comment]
Use `firstOrError()`

**Comment by worldsnas** [comment]
oh, that was easy.
thank you so much. save the day
