### ISSUE TITLE
Expose an api for entirely non-null preferences

### ISSUE THREAD

**Issue by pforhan** [f2prateek/rx-preferences#122]
It'd be very nice for cases where you don't have a null default and don't ever set null into a preference to have a clean non-null version of Preference.  Would make kotlin interop better as well.

Looking through issue history, seems like there's a lot of conflicting threads pulling the library around nulls.  Rather than force a change to existing Preferences a new set of NonNullPreference (though with a better name?) methods would be an easy change.

I could whip up a pull if this is appealing.

**Comment by f2prateek** [comment]
> Would make kotlin interop better as well.

Can you describe some examples where the Kotlin interop can be improved?

**Comment by pforhan** [comment]
Basically I wouldn't have to be reading (for example) `Boolean?` or need to use `!!` to assert that it really wasn't null.

**Comment by NightlyNexus** [comment]
are you on the 2.0.0? i thought null was already banned in preferences now?

**Comment by pforhan** [comment]
oops, no, still on an older version.

**Comment by pforhan** [comment]
looks like this has been resolved, so sorry.  I checked issues but not the latest code, oops.
