### ISSUE TITLE
StringAdapter returns null

### ISSUE THREAD

**Issue by rjrjr** [f2prateek/rx-preferences#131]
`StringAdapter` assumes that it will never read a `null` from `SharedPreferences.getString`, which is not true. It enforces this invariant with an `assert`, which is a no-op in most builds:

```kotlin
    assert value != null; // Not called unless key is present.
```

`SharedPreferences` is happy to record null values, and report that they have been set. For example, this test hits the `assertion` above:

```kotlin
  @Test fun sharedPreferencesStringAdapterIsNullDefensive() {
    sharedPreferences.edit().putString("fnord", null).commit()
    assertThat(sharedPreferences.contains("fnord"))
    assertThat(sharedPreferences.getString("fnord", null)).isNull()

    val pref = createPreferences().getString("fnord")
    // We never reach the assertThat below, due to the assert in the getString call above.

    assertThat(pref.get()).isEqualTo("")
  }
```

**Comment by rjrjr** [comment]
We're hitting this issue in code that I recently converted to {{RxSharedPreferences}}. It's reading existing string values, and apparently some of them are null.

**Comment by rjrjr** [comment]
Should be able to fix this in `RealPreference.get`, if we just stop relying on `SharedPreferences.contains`.

**Comment by rjrjr** [comment]
Similar test as an addition to `PreferenceTest`:

```java
  @Test public void legacyNullString() {
    preferences.edit()
        .putString("someString", null)
        .commit();

    assertThat(rxPreferences.getString("someString").get()).isEqualTo("");
  }
```

**Comment by f2prateek** [comment]
Similar to https://github.com/f2prateek/rx-preferences/issues/123
