### ISSUE TITLE
Build failure on master

### ISSUE THREAD

**Issue by preetha1326** [f2prateek/rx-preferences#145]
Running `./gradlew rx-preferences:build` gives the error quoted below(100s of them).
As the searches suggested, I tried running: 

`npm install --save-dev jetifier
npx jetify`

but still getting the same errors.If any one had faced this and have a solution please share

Error:
> symbol:   class NonNull
>   location: class StringSetAdapter
> /Users/preetha/Development/f2prateek-rx-preferences/rx-preferences/src/main/java/com/f2prateek/rx/preferences2/StringSetAdapter.java:19: error: cannot find symbol
>   @Override public void set(@NonNull String key, @NonNull Set<String> value,
>                                                   ^
>   symbol:   class NonNull
>   location: class StringSetAdapter
>

**Comment by rogerhu** [comment]
The quick fix is:
```
     task androidJavadocs(type: Javadoc) {
     source = android.sourceSets.main.java.srcDirs
     classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
-
+    classpath += files(android.libraryVariants.collect { variant ->
+      variant.getJavaCompileProvider().get().classpath.files
+    })
     if (JavaVersion.current().isJava8Compatible()) {
       allprojects {
         tasks.withType(Javadoc) {
```

However, you should be able to use the new Maven publish library for Android apps now instead of the `gradle/gradle-mvn-push.gradle` task:

https://developer.android.com/studio/publish-library/upload-library

**Comment by preetha1326** [comment]
This fixed the issue. Thank you @rogerhu
