### ISSUE TITLE
Provide read-only super-interface for Preference

### ISSUE THREAD

**Issue by dalewking** [f2prateek/rx-preferences#31]
When using injection to inject preferences it is a good idea to differentiate between read-only and read-write access to the preference. I would like to see a super-interface for Preference that only exposes the read methods, Ideally, this would be the methods get and asObservable. You might want this interface to extend javax.inject.Provider which is an interface for just the get method.

**Comment by f2prateek** [comment]
Not sure if that's useful in the core library. But you could easily write your own `Preference.Adapter`:

```java
final class ReadOnlyAdapter implements Preference.Adapter<T> {
  final Preference.Adapter<T> delegate;

  ReadOnlyAdapter(Preference.Adapter<T> delegate) {
    this.delegate = delegate;
  }

  @Override public T get(String key, SharedPreferences preferences) {
    return delegate.get(key, preferences);
  }

  @Override public void set(String key, T value, SharedPreferences.Editor editor) {
    throw new UnsupportedOperationException();
  }
}
```

**Comment by JakeWharton** [comment]
Plus requiring JSR330 is strange considering this library has nothing to do
with it.

**Comment by dalewking** [comment]
That would be a good solution if my goal was to add a lot of bloat to my
code. You seriously think I should create another instance of preferences
class with another set of references to its half dozen instance variables
and another observable chain for every preference!?!? I think I'd pass over
just casting to a super interface.

And I neglected to notice that Preference itself is a final class that can
only be created through static methods in another class. You have created a
unit test nightmare. You also need to extract an interface for all the
methods in Preference (actually probably better to make Preference the
interface and extract the implementation to another class). When using
dependency injection the classes needing access to the Preference should
inject the interface instead of a concrete class. That makes creating mock
preferences for unit testing a breeze.

I already have my own similar classes for preferences which I was hoping to
replace with this library, but the lack of proper interfaces would make
this a huge step backwards.

**Comment by dalewking** [comment]
It comes from when you are injecting the preferences. In my own similar
classes, I inject the interface for the full preference only in classes
that will be changing the preference. For classes that only need the
current value, I inject Provider<T>. Provider is just a convenient
interface for get. It probably is not necessary with a proper read-only
interface.

**Comment by JakeWharton** [comment]
Inheritance is mostly an anti-pattern anyway. The classes are easily unit
testable in on-device unit tests or instrumentation tests. Mocking isn't a
real solution.

**Comment by dalewking** [comment]
Implementation inheritance is certainly often an anti-pattern, but I said nothing about adding implementation inheritance. Exposing an API through interfaces is definitely not an anti-pattern and to me pretty much the only way to expose an API.

Saying that you can test it through on-device testing is just reinforcing my statement that the API is a unit testing nightmare. You cannot create an instance of Preferences currently without an instance of SharedPreferences. This is horrible. If you add super-interfaces it is trivial to unit test classes that depend on preferences through the interface. Mocking is definitely a solution.

Let's say you do what I suggested and make Preference actually be an interface like it should be and you have a class that has an injection like:

    @inject Preference<Boolean> fooPreference;

In your unit test with Mockito you can just do:

   @Mock Preference<Boolean> mockFooPreference;

You inject this into your class under test. and in a particular test you might do:

    when(mockFooPreference.get()).thenReturn(false);

or if you need it as observable you do:

   when(mockfoorPreference.asObservable()).thenReturn(Observable.just(false));

Why is this not a "real solution"?

**Comment by JakeWharton** [comment]
You can just inject the `Observable<Boolean>` for consumption-only and replace that with `Observable.just(false)` in your tests. There's no need to mock.

**Comment by dalewking** [comment]
That could handle the case of the readonly aspect of the Preferences (which granted was the initial impetus for this issue), but does not handle the case of unit testing a class that needs to both read and write a preference. The API for the preference is to a class that you cannot create without a SharedPreferences object. As I later added Preference should be made into an interface that just defines the methods to access a Preference.

**Comment by dalewking** [comment]
I am going to close this issue asking for a read-only super interface, but open another issue for turning Preference into an interface.
