### ISSUE TITLE
Expose SharedPreferences.contains(String key)

### ISSUE THREAD

**Issue by troyjperales** [f2prateek/rx-preferences#34]
Easy enough to add myself, but just wondering if not exposing this was intentional.

**Comment by JakeWharton** [comment]
The library discourages accessing preferences as a key/value store. Why do you want this?

**Comment by troyjperales** [comment]
Current use case may not be reason enough to add, but I am injecting an "isFirstRun" preference that needs to be updated to false if it's already there. I had been using only RxPreferences up until now, but this might be better as a regular preference since I don't really need the "Rx".
