### ISSUE TITLE
Add a way to store a Preference value synchronously

### ISSUE THREAD

**Issue by varyoo** [f2prateek/rx-preferences#42]
I need to store a value synchronously, something like this:

```java
public boolean setSync(@Nullable T value) {
    SharedPreferences.Editor editor = preferences.edit();
    if (value == null) {
      editor.remove(key);
    } else {
      adapter.set(key, value, editor);
    }
    return editor.commit(); // instead of editor::apply
  }
```

See: http://stackoverflow.com/questions/5960678/whats-the-difference-between-commit-and-apply-in-shared-preference

By the way, maybe `Preference::asAction` should be updated to execute the storing process synchronously as well.

Thanks for this great library.

**Comment by JakeWharton** [comment]
`apply` is both atomic and synchronous in the memory cache of preferences, it just doesn't persist to disk. Do you really need a write synchronously persisted to disk?

**Comment by varyoo** [comment]
Wow you're so fast, I don't need it indeed, sorry for the trouble, and thanks for the info!

**Comment by brycehendrix** [comment]
@JakeWharton it would be very nice. We have a case where the Api endpoint is stored in a preference, then the process is restarted. Most of the time the process is restarted before the preference is written to disk and the preference change is lost.
