### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by bryanstern** [f2prateek/rx-preferences#47]
It appears that the old backpressure solution misbehaves when a project uses the latest version of RxJava (1.1.5).

If you have a new empty `SharedPreference` instance and try to observe a String in it, `null` will be emitted non stop when subscribed to. This behavior occurs in 1.0.1, but is fixed if I build my project against the current master which has https://github.com/f2prateek/rx-preferences/pull/39 in it.

Could you cut a release with the updated backpressure solution?

**Comment by f2prateek** [comment]
Just published, thanks for the reminder!
