### ISSUE TITLE
RxJava 2

### ISSUE THREAD

**Issue by PaulWoitaschek** [f2prateek/rx-preferences#49]
I'm looking forward for adopting RxJava 2. Therefore this library needs to be updated (and partly rewritten).
As RxJava does not accept nulls any more, it might make sense to split the preference class in two types:
One that emits a `java.util.Optional` and one that emits the raw type. Here the preference creation must differentiate and check the initial value that will be used as a default.

Another solution could be to just make everything an optional, but that wouldn't result in a too fluent api usage.

If a decision on this would be made by the library owner I could do a pull request.

**Comment by f2prateek** [comment]
Seems reasonable to me, I haven't been really keeping up with the changes for RxJava 2 so might take a while for me to get to it.

**Comment by JakeWharton** [comment]
Nothing should be done until 2.0 final is released. And if only there was a
presentation you could attend next week at a conference you'll be attending
to learn about RxJava 2... hmmm.....

**Comment by f2prateek** [comment]
I did some preliminary work for updating to rxjava 2 https://github.com/f2prateek/rx-preferences/tree/2.x

**Comment by JakeWharton** [comment]
`emitter.setCancellable` should be done before registering the listener. This ensures that synchronous emissions when adding the listener and a synchronous unsubscribe actually run the unsubscribe action.

**Comment by PaulWoitaschek** [comment]
RxJava 2 is out

**Comment by r-gurzkowski** [comment]
Any plans on finishing rxjava 2.x compatibility? I can offer my help.

**Comment by netimen** [comment]
This would be really great

**Comment by f2prateek** [comment]
Initial cut in 2.0.0-RC1. Though there is some work to be done still to make backpressure work out of the box (maybe via https://github.com/f2prateek/rx-preferences/tree/flowable).

**Comment by PaulWoitaschek** [comment]
I don't get it. How do you handle null? If I understand correctly you just let it crash?

**Comment by f2prateek** [comment]
Null what?

**Comment by PaulWoitaschek** [comment]
Null values. get() ist Nullable and of you call onNext with a null you get an NPE

**Comment by f2prateek** [comment]
Yup. For now make sure you supply a default value if you expect your preference values to be null. In the future, we could handle this by returning `Observable<Preference<T>>` instead of `Observable<T>`.

**Comment by PaulWoitaschek** [comment]
Well then you should catch that error and throw an appropriate one. 
I think it's appropriate to make the default value strictly NonNull and throw an NPE when the default value is null. Thats consistent to RxJava 2. 
If people do not have a default value they should use an Optional.
