### ISSUE TITLE
Cache values in RealPreference

### ISSUE THREAD

**Issue by NightlyNexus** [f2prateek/rx-preferences#72]
I imagine this has been considered long ago, but I didn't find any discussions in GH, at least. I'm considering doing this in my fork, so that's mostly why I'm filing ha.

It should be easy enough to be thread-safe, but I don't know how much speed there is to be gained from skipping the SharedPreference disk read.

**Comment by JakeWharton** [comment]
Doesn't shared preference do this for us?

**Comment by f2prateek** [comment]
SharedPreferences does cache the raw type in an in-memory map. I think the ask here is to cache the values after the converter has parsed it? 

Used to this earlier https://github.com/f2prateek/rx-preferences/pull/4.

**Comment by NightlyNexus** [comment]
Oh, yeah, SharedPreference does that. 🐑 

But, yeah, it would still be helpful to do this to skip the converter.
What does #4 have to do with this?

**Comment by NightlyNexus** [comment]
Oh, that'd be a breaking change if somebody insanely mutated state in a converter. ha.

**Comment by f2prateek** [comment]
Ah sorry, that might have not been clear. #4 was specifically fixing the caching bug we used to have from my original implementation. This was in 0.1.x which was pretty much re-written from scratch for v1 though.
