### ISSUE TITLE
2.0: Make set() @NonNull

### ISSUE THREAD

**Issue by PaulWoitaschek** [f2prateek/rx-preferences#78]
To be consistent with the recent changes about nullity I want to suggest to make `set` explicity `@NonNull` as null itself is not supported.

For deletion there is the explicit method `delete`

**Comment by NightlyNexus** [comment]
I've also considered this.
But, I think is consistent behavior with `SharedPreferences.Editor.set(null)` which is nullable to delete.
And, I worry that some consumer code has nullable values that aren't particularly special, and it would be a burden to do a null check at such call sites.
Not sure, though!

**Comment by PaulWoitaschek** [comment]
I find it confusing. I think it's more important to be consistent with RxJava than the flawed SharedPreferences API. 
With a set(null) I'd expect the library to emit null afterwards.
Also I think that setting null is rather error prone because an accidental null could delete the preference which is potentially​ harmful. A delete is explicit.

**Comment by f2prateek** [comment]
The use case here is to be able to use it as an action to be able to delete preferences easily (without having your own if check).

What else would you expect set with null to do other than delete given that only non null values can be emitted? This might have been a source of confusion earlier but I don't think it would be now in the NonNull world - where null values simply cannot be emitted.

**Comment by f2prateek** [comment]
Actually I think I see what you mean now. Null values are not emitted anymore, so there's no reason for the consumer to accept null as well. Which means `set(null)` isn't needed for this case.

Set(null) does allow for convenience if you're using it directly (to avoid your own null check). But might not really be that useful.

Personally I've never needed to use `set(null)` directly, so am open to making it non-null.

**Comment by PaulWoitaschek** [comment]
I don't use I either. When I set it it's an developer error and I'm having a bug that is about to accidentally delete a preference.

But for me it's mostly about a consistent API and as v2 is not released there can still be breaking changes.

Feel free to decide and close. Thanks for the library :)

**Comment by f2prateek** [comment]
@PaulWoitaschek Send a PR!
