### ISSUE TITLE
Unset string value triggers error

### ISSUE THREAD

**Issue by vekexasia** [f2prateek/rx-preferences#82]
Hello, 
it appears that maven version does not have  aDEFAULT_STRING = "" fallback when the key is not set.

I'm referring to this line of code: https://github.com/f2prateek/rx-preferences/blob/master/rx-preferences/src/main/java/com/f2prateek/rx/preferences2/RxSharedPreferences.java#L25

That causes the app to crash due to "null" support of rxjava2.

Is there a reason why fixed version was not released to maven yet?

**Comment by f2prateek** [comment]
You can set the defualt value yourself for now. The code on master will be released likely after https://github.com/f2prateek/rx-preferences/pull/81 is merged.
