### ISSUE TITLE
Setting nulls to SharedPreferences breaks the flow for pre-lollipop devices

### ISSUE THREAD

**Issue by vkislicins** [f2prateek/rx-preferences#83]
Thanks for the library! I'm looking into using it for production in my app, however, there seems to be a weird issue on pre-lollipop devices with null values in `SharedPreferences`. Might be related to the fact that I'm using RxJava2, however `onError` is not emitted.

        return  getName()
                        .subscribeOn(mSchedulerProvider.io())
                        .observeOn(mSchedulerProvider.ui())
                        .subscribe((name) -> {
                            mLogger.d(TAG,".onNext() - entered");
                        }, (e) ->  {
                            mLogger.e(TAG,".onError() - entered");
                        }, () -> {
                            mLogger.d(TAG," onComplete() - entered");
                });

        public Observable<String> getName() {
             return mName.asObservable().onErrorResumeNext(Observable.just(EMPTY_STRING));
        }

In the example above, `onNext` will be called when I'm setting a new name, i.e. saving the name to the shared preferences. However, if I save a null, instead of handling that, the `getName` chain will stop reacting without any events (`onError` and `onComplete` are not getting called). Setting any name after attempting to set null will not cause an event to trigger.

This behavior is only seen on pre-lollipop devices - the rest are working fine. I'm using `rx-preferences:2.0.0-RC1`

Also, if I handle nulls before saving to the `SharedPreferences`, the issue gets resolved. Therefore, it is something to do with handling nulls. As a workaround:

    public void setUserName(String userName) {
        savePref(PREF_USER_NAME, userName != null ? userName : EMPTY_STRING);
    }

**Comment by NightlyNexus** [comment]
Before Lollipop, there was a bug in SharedPreferences that did not delete the preference when setting it to null (as the doc said it should). Fixed here: r.android.com/74070/.

So, if this was a key you were using before using this library, the `contains` check might be lying.
Not sure exactly if that's the issue here.

**Comment by f2prateek** [comment]
Sounds like there isn't any action to take in this library? The new release will disallow nulls from being saved anyway, though there isn't much we can do if `contains` is lying I think. Feel free to reopen if you think otherwise.
