### ISSUE TITLE
Is the default value useful?

### ISSUE THREAD

**Issue by NightlyNexus** [f2prateek/rx-preferences#90]
On the projects I work on, I never use the default value, and I always check `isSet()` first. If my data isn't there, I need to get it from some source (or throw an ISE, as the case may be).
Especially with disallowing null default values, I need to take care that that check exists everywhere.

Is it useful to have `Preference.get()` return a default value when the value is not set?

I may be missing good use cases.

**Comment by f2prateek** [comment]
The core reason that it's for parity with the SharedPreferences interface.

I do think there are use cases, because having to do an `isSet` check everywhere can be a pain.

For instance, in Device Frame Generator I have some "default" settings https://github.com/f2prateek/device-frame-generator/blob/master/src/main/java/com/f2prateek/dfg/prefs/PreferencesModule.java#L41. Rather than have a check for this in the code everywhere I read the preference, it's easier to assume there will be a value set.

**Comment by NightlyNexus** [comment]
Oh, yep! Simple switches are great use cases. Telecine does the same.
Thanks!

**Comment by NightlyNexus** [comment]
I have thought about this more, and I'd like to discuss this further if that's okay.

We could remove default values but still making them easy to set for users.

RxPreferences.getBoolean(key) => returns a RealPreference that throws in `get` without being set first.

RxPreferences.getBoolean(key, defaultValue) => same as above except this factory method does an initial setup:
```java
preference = getBoolean(key)
if (!preference.isSet()) preference.set(defaultValue)
return preference
```

Con: Removing the default value does not mirror the SharedPreference API anymore.
Pro: No more sentinel values for defaults. I keep finding these values both awkward. They exist but are never used, assuming isSet checks are done correctly.

**Comment by NightlyNexus** [comment]
I'm going to try this out in a fork and see how I like it. I'm also okay with using a fork if it's not a big use case for others.
I seem to have lots of values that need isSet checks.

**Comment by NightlyNexus** [comment]
i realized that my idea above makes `delete` awkward for preferences created with a set value.

i think i'll end up having a Preference and a PreferenceWithDefaultValue for my needs. my common use case is getting a value that is supposed to be set already before usage, and i only have a few places that want proper defaults.

i don't know of a better way to expose such behavior, and i think it would be a separate library.
