### ISSUE TITLE
Loose final?

### ISSUE THREAD

**Issue by Ghedeon** [f2prateek/rx-preferences#91]
Awesome concept, first of all, thank you!

Now, I got it, it's a library, public API, we have to be dogmatic and stuff, but is it really that important to have `Preference` final? It makes it impossible to mock, leads to boilerplate code just to get an instance of it and what's more annoying: makes `@InjectMocks` useless in tests.

Thank you.

**Comment by JakeWharton** [comment]
There's no reason to make `Preference` non-final. Nothing is to be gained from ever extending it. The only possible course of action to support mocking is extracting an interface which has come up before.

**Comment by serj-lotutovici** [comment]
[`Preference`](https://github.com/f2prateek/rx-preferences/blob/master/rx-preferences/src/main/java/com/f2prateek/rx/preferences2/Preference.java) is an interface since `2.x`

**Comment by JakeWharton** [comment]
Problem solved

**Comment by Ghedeon** [comment]
I should have checked that before, thanks!
