### ISSUE TITLE
`getObject` should not have `@Nullable` annotation for default value.

### ISSUE THREAD

**Issue by AndrewReitz** [f2prateek/rx-preferences#95]
The default value can not be null, so the annotation should probably be `@NonNull` instead of `@Nullable`

https://github.com/f2prateek/rx-preferences/blob/master/rx-preferences/src/main/java/com/f2prateek/rx/preferences2/RxSharedPreferences.java#L131

**Comment by NightlyNexus** [comment]
Yep, nice catch! Send a PR?

**Comment by PaulWoitaschek** [comment]
@f2prateek What about a 2.0 release?

**Comment by f2prateek** [comment]
https://github.com/f2prateek/rx-preferences/commit/82f8e2b8c0da98610824c7ac2e359b0861a09fc4

**Comment by PaulWoitaschek** [comment]
I meant a 2.0 non-rc release.
