### ISSUE TITLE
Question: why do we need asConsumer()?

### ISSUE THREAD

**Issue by tmtron** [f2prateek/rx-preferences#96]
e.g.  [SampleActivity.java line 62](https://github.com/f2prateek/rx-preferences/blob/master/rx-preferences-sample/src/main/java/com/f2prateek/rx/preferences2/sample/SampleActivity.java#L62) :

`.subscribe(preference.asConsumer()));`

This is the same as using the setter method, right?
`.subscribe(preference::set));`

Is there any advantage of using `asConsumer()`?

**Comment by JakeWharton** [comment]
If you don't have method references available.

**Comment by tmtron** [comment]
So simple :) Thanks.
That answers also my [SO Question "Setters: Consumer vs. direct method call"](https://stackoverflow.com/a/44384293/6287240)
